CONFIG_FSL_OSA_TASK_ENABLE=n
CONFIG_IP_REASS_MAX_PBUFS=4
CONFIG_LWIP_ASSERT_CORE_LOCKED( )="sys_check_core_locking()"
CONFIG_LWIP_DHCP=y
CONFIG_LWIP_ICMP=y
CONFIG_LWIP_IPV6=n
CONFIG_LWIP_NETCONN=n
CONFIG_LWIP_NETIF_EXT_STATUS_CALLBACK=y
CONFIG_LWIP_OPT_H_CODE_LINE_1="void sys_check_core_locking(void);"
CONFIG_LWIP_PROVIDE_ERRNO=y
CONFIG_LWIP_SINGLE_NETIF=y
CONFIG_LWIP_SOCKET=n
CONFIG_LWIP_STATS=n
CONFIG_LWIP_TCP=y
CONFIG_LWIP_UDP=y
CONFIG_MCUX_COMPONENT_CMSIS_DSP_Source=y
CONFIG_MCUX_COMPONENT_component.audio_sai_edma_adapter=y
CONFIG_MCUX_COMPONENT_component.igpio_adapter=y
CONFIG_MCUX_COMPONENT_component.lpi2c_adapter=y
CONFIG_MCUX_COMPONENT_component.phyksz8081=y
CONFIG_MCUX_COMPONENT_component.silicon_id=y
CONFIG_MCUX_COMPONENT_driver.dmamux=y
CONFIG_MCUX_COMPONENT_driver.edma=y
CONFIG_MCUX_COMPONENT_driver.enet=y
CONFIG_MCUX_COMPONENT_driver.gpt=y
CONFIG_MCUX_COMPONENT_driver.lpi2c=y
CONFIG_MCUX_COMPONENT_driver.sai=y
CONFIG_MCUX_COMPONENT_driver.sai_edma=y
CONFIG_MCUX_COMPONENT_driver.wm8960=y
CONFIG_MCUX_COMPONENT_middleware.lwip.kinetis_ethernetif=y
CONFIG_MCUX_COMPONENT_middleware.lwip=y
CONFIG_MCUX_COMPONENT_middleware.usb.common_header=y
CONFIG_MCUX_COMPONENT_middleware.usb.device.common_header=y
CONFIG_MCUX_PRJSEG_component.osa_interface.generated_config=y
CONFIG_MCUX_PRJSEG_middleware.lwip.generated_config=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MEMP_NUM_PBUF=12
CONFIG_MEMP_NUM_REASSDATA=2
CONFIG_MEMP_NUM_SYS_TIMEOUT="8"
CONFIG_MEMP_NUM_TCP_PCB=8
CONFIG_MEMP_NUM_TCP_PCB_LISTEN=2
CONFIG_MEMP_NUM_TCP_SEG=16
CONFIG_MEMP_NUM_UDP_PCB=4
CONFIG_MEM_ALIGNMENT=4
CONFIG_MEM_SIZE=12288
CONFIG_NO_SYS=y
CONFIG_PBUF_POOL_SIZE=8
CONFIG_TCP_LISTEN_BACKLOG=y
CONFIG_TCP_MSS=1460
CONFIG_TCP_QUEUE_OOSEQ=n
CONFIG_TCP_SND_BUF="(4 * TCP_MSS)"
CONFIG_TCP_SND_QUEUELEN="((3 * TCP_SND_BUF) / TCP_MSS)"
CONFIG_TCP_TTL=255
CONFIG_TCP_WND="(6 * TCP_MSS)"
CONFIG_UDP_TTL=255
CONFIG_USB_DEVICE_CONFIG_AUDIO=1
CONFIG_USB_DEVICE_CONFIG_GET_SOF_COUNT=y
CONFIG_USB_DEVICE_CONFIG_ROOT2_TEST=y
