/* generated by tools/make_decimator.py - do not edit */
#ifndef _ROOMCORR_RESAMPLE_H_
#define _ROOMCORR_RESAMPLE_H_

#include "arm_math.h"

#define RC_DECIM_TAPS  (127U)
#define RC_DECIM_DELAY (63U)  /* samples at the 96 kHz rate */

static const float32_t rc_decim_fir[RC_DECIM_TAPS] = {
    -0x1.8c8417bc28e79p-17f, 0x1.475a3f24c3396p-63f, 0x1.d2ae8e06e640dp-16f, -0x1.f000ec5bb09e9p-62f, -0x1.b9dc013e9430dp-15f, -0x1.9eb1069a9623bp-74f,
    0x1.75f8ef97628dbp-14f, -0x1.c8818f08fb43fp-62f, -0x1.26bb40c14fce4p-13f, 0x1.5e2cb4c7e1c9cp-60f, 0x1.b99ce4ffb65bap-13f, 0x1.25e2078d0857ap-60f,
    -0x1.3e573b3247477p-12f, -0x1.a1b3c2b379391p-63f, 0x1.bd17a95777538p-12f, -0x1.af2f6a30bafe9p-60f, -0x1.2f6843ed1de0fp-11f, 0x1.3afc50f67f4cdp-58f,
    0x1.94f6aea33ac7bp-11f, -0x1.40628f7f6ee27p-57f, -0x1.09645249ee365p-10f, -0x1.4d8de13df8306p-60f, 0x1.566a57e46a2b0p-10f, -0x1.0abbe77158300p-58f,
    -0x1.b3c1ec89ebff3p-10f, 0x1.94e36c64796e0p-57f, 0x1.11f17165529edp-9f, -0x1.7ba366d53e17bp-58f, -0x1.54cbaa9765d49p-9f, -0x1.399bf0ec4e903p-58f,
    0x1.a408f3cd86739p-9f, -0x1.006414c41e229p-57f, -0x1.00c3b556153a2p-8f, 0x1.ad8e8fe088817p-56f, 0x1.37c14b7c6be67p-8f, -0x1.4ad2ac145899ap-57f,
    -0x1.785c2edaad1eap-8f, -0x1.c79fa00f1bd45p-57f, 0x1.c450973de691fp-8f, -0x1.99b3f02e2c05ap-57f, -0x1.0ef1c33aa525bp-7f, 0x1.98b87bca6616ap-55f,
    0x1.4413f8d81d37bp-7f, -0x1.e8ae3f9a629ebp-57f, -0x1.83b82b6b46c68p-7f, 0x1.07568af16a8c6p-56f, 0x1.d1089447d399ap-7f, -0x1.1969c95af5765p-56f,
    -0x1.186fd2c8ea3e2p-6f, 0x1.2a4028d3dd7bap-56f, 0x1.558c9abed46c3p-6f, -0x1.398c2d559b49cp-56f, -0x1.a6a9bf138964dp-6f, 0x1.4705a5c9e9177p-56f,
    0x1.0c56f98801328p-5f, -0x1.526ba6bd8bffbp-56f, -0x1.63a7b65a80badp-5f, 0x1.5b86599ca66d6p-56f, 0x1.fd5bec90277e5p-5f, -0x1.62289058e06c9p-56f,
    -0x1.aeedb7b0d8a7dp-4f, 0x1.66310f480681fp-56f, 0x1.45a4e3236354fp-2f, 0x1.00005fe0559f8p-1f, 0x1.45a4e3236354fp-2f, 0x1.66310f480681fp-56f,
    -0x1.aeedb7b0d8a7dp-4f, -0x1.62289058e06c9p-56f, 0x1.fd5bec90277e5p-5f, 0x1.5b86599ca66d6p-56f, -0x1.63a7b65a80badp-5f, -0x1.526ba6bd8bffbp-56f,
    0x1.0c56f98801328p-5f, 0x1.4705a5c9e9177p-56f, -0x1.a6a9bf138964dp-6f, -0x1.398c2d559b49cp-56f, 0x1.558c9abed46c3p-6f, 0x1.2a4028d3dd7bap-56f,
    -0x1.186fd2c8ea3e2p-6f, -0x1.1969c95af5765p-56f, 0x1.d1089447d399ap-7f, 0x1.07568af16a8c6p-56f, -0x1.83b82b6b46c68p-7f, -0x1.e8ae3f9a629ebp-57f,
    0x1.4413f8d81d37bp-7f, 0x1.98b87bca6616ap-55f, -0x1.0ef1c33aa525bp-7f, -0x1.99b3f02e2c05ap-57f, 0x1.c450973de691fp-8f, -0x1.c79fa00f1bd45p-57f,
    -0x1.785c2edaad1eap-8f, -0x1.4ad2ac145899ap-57f, 0x1.37c14b7c6be67p-8f, 0x1.ad8e8fe088817p-56f, -0x1.00c3b556153a2p-8f, -0x1.006414c41e229p-57f,
    0x1.a408f3cd86739p-9f, -0x1.399bf0ec4e903p-58f, -0x1.54cbaa9765d49p-9f, -0x1.7ba366d53e17bp-58f, 0x1.11f17165529edp-9f, 0x1.94e36c64796e0p-57f,
    -0x1.b3c1ec89ebff3p-10f, -0x1.0abbe77158300p-58f, 0x1.566a57e46a2b0p-10f, -0x1.4d8de13df8306p-60f, -0x1.09645249ee365p-10f, -0x1.40628f7f6ee27p-57f,
    0x1.94f6aea33ac7bp-11f, 0x1.3afc50f67f4cdp-58f, -0x1.2f6843ed1de0fp-11f, -0x1.af2f6a30bafe9p-60f, 0x1.bd17a95777538p-12f, -0x1.a1b3c2b379391p-63f,
    -0x1.3e573b3247477p-12f, 0x1.25e2078d0857ap-60f, 0x1.b99ce4ffb65bap-13f, 0x1.5e2cb4c7e1c9cp-60f, -0x1.26bb40c14fce4p-13f, -0x1.c8818f08fb43fp-62f,
    0x1.75f8ef97628dbp-14f, -0x1.9eb1069a9623bp-74f, -0x1.b9dc013e9430dp-15f, -0x1.f000ec5bb09e9p-62f, 0x1.d2ae8e06e640dp-16f, 0x1.475a3f24c3396p-63f,
    -0x1.8c8417bc28e79p-17f,
};

#endif
