/* generated by tools/make_filter.py - do not edit */
#ifndef _ROOMCORR_PARAMS_H_
#define _ROOMCORR_PARAMS_H_

#define RC_SAMPLE_RATE   (48000U)
#define RC_CHANNELS      (2U)
#define RC_BLOCK         (1024U)   /* B, frames per partition */
#define RC_FFT_SIZE      (2048U)   /* N = 2B */
#define RC_PARTITIONS    (16U)   /* P */
#define RC_TAPS          (16384U)
#define RC_FILTER_BYTES  (262144U)

#endif
