#!/usr/bin/env python3
"""Embed the control page as C rodata."""
HTML = r"""<!doctype html><html><head><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>RT1050 Room Correction</title><style>
body{font:14px/1.4 system-ui,sans-serif;margin:0;padding:1rem;background:#14161a;color:#e6e8eb}
h1{font-size:1.1rem;margin:0 0 .8rem}h2{font-size:.85rem;text-transform:uppercase;
letter-spacing:.06em;color:#8b949e;margin:1.4rem 0 .5rem;font-weight:600}
.card{background:#1c1f25;border:1px solid #2a2f38;border-radius:8px;padding:1rem;
max-width:760px;margin:0 auto 1rem}
.row{display:flex;align-items:center;gap:.6rem;margin:.35rem 0}
.row label{width:5.5rem;color:#8b949e;font-variant-numeric:tabular-nums}
.row input[type=range]{flex:1}
.row output{width:3.6rem;text-align:right;font-variant-numeric:tabular-nums}
button{background:#2d333b;color:#e6e8eb;border:1px solid #3d444d;border-radius:6px;
padding:.45rem .9rem;cursor:pointer;font:inherit}
button:hover{background:#373e47}
button.on{background:#1f6f3f;border-color:#2ea043}
button.off{background:#7a2c2c;border-color:#c04141}
#stat{color:#8b949e;font-variant-numeric:tabular-nums;white-space:pre-wrap}
#msg{margin-left:.6rem}
</style></head><body>
<div class=card>
<h1>RT1050 Room Correction</h1>
<div class=row><button id=byp></button><span id=msg></span></div>
<h2>Preamp</h2>
<div class=row><label>preamp</label><input type=range id=pre min=-40 max=12 step=.5 value=0>
<output id=preo>0.0 dB</output></div>
<h2>16-band EQ</h2><div id=eq></div>
<div class=row><button onclick=flat()>Flatten EQ</button></div>
<h2>Impulse response</h2>
<div class=row><input type=file id=ir accept=".wav"><button onclick=up()>Upload</button></div>
<div class=row><span id=irmsg></span></div>
<h2>Status</h2><div id=stat></div>
</div>
<script>
const F=[20,31,50,80,125,200,315,500,800,"1.25k","2k","3.15k","5k","8k","12.5k","20k"];
let eqv=new Array(16).fill(0),byp=false;
const eqd=document.getElementById('eq');
F.forEach((f,i)=>{const d=document.createElement('div');d.className='row';
 d.innerHTML=`<label>${f} Hz</label><input type=range min=-12 max=12 step=.5 value=0 id=e${i}>
 <output id=o${i}>0.0 dB</output>`;eqd.appendChild(d);
 d.querySelector('input').oninput=e=>{eqv[i]=+e.target.value;
  document.getElementById('o'+i).textContent=eqv[i].toFixed(1)+' dB';set({['eq'+i]:eqv[i]});};});
const pre=document.getElementById('pre');
pre.oninput=e=>{document.getElementById('preo').textContent=(+e.target.value).toFixed(1)+' dB';
 set({preamp:+e.target.value});};
document.getElementById('byp').onclick=()=>set({bypass:byp?0:1});
function flat(){const o={};for(let i=0;i<16;i++){o['eq'+i]=0;eqv[i]=0;
 document.getElementById('e'+i).value=0;document.getElementById('o'+i).textContent='0.0 dB';}set(o);}
function set(o){fetch('/api/set?'+new URLSearchParams(o)).then(r=>r.json()).then(render);}
function render(s){byp=!!s.bypass;const b=document.getElementById('byp');
 b.textContent=byp?'Correction BYPASSED':'Correction ENGAGED';b.className=byp?'off':'on';
 document.getElementById('stat').textContent=
  `filter    ${s.filter}\ntaps      ${s.taps} @ ${s.srcRate} Hz source\ncpu       ${s.cpu}%`+
  `\nblocks    ${s.blocks}\nunderruns ${s.underruns}\nclips     ${s.clips}\naddress   ${s.ip}`;}
function up(){const f=document.getElementById('ir').files[0];if(!f)return;
 document.getElementById('irmsg').textContent='uploading '+f.size+' bytes, audio will glitch...';
 f.arrayBuffer().then(b=>fetch('/api/ir',{method:'POST',body:b})).then(r=>r.json())
 .then(j=>{document.getElementById('irmsg').textContent=j.ok?('loaded: '+j.filter):('failed: '+j.msg);
  refresh();}).catch(e=>{document.getElementById('irmsg').textContent='failed: '+e;});}
function refresh(){fetch('/api/status').then(r=>r.json()).then(s=>{render(s);
 if(!document.activeElement||document.activeElement.type!=='range'){
  pre.value=s.preamp;document.getElementById('preo').textContent=(+s.preamp).toFixed(1)+' dB';
  s.eq.forEach((v,i)=>{eqv[i]=v;document.getElementById('e'+i).value=v;
   document.getElementById('o'+i).textContent=(+v).toFixed(1)+' dB';});}});}
refresh();setInterval(refresh,2000);
</script></body></html>"""

data = HTML.encode()
with open('usb_dac32/roomcorr_web.h', 'w') as f:
    f.write("/* generated by tools/make_web.py - do not edit */\n")
    f.write("#ifndef _ROOMCORR_WEB_H_\n#define _ROOMCORR_WEB_H_\n\n#include <stdint.h>\n\n")
    f.write(f"#define rc_web_page_len ({len(data)}U)\n\n")
    f.write("static const char rc_web_page[] =\n")
    for i in range(0, len(data), 72):
        chunk = data[i:i+72]
        esc = "".join('\\"' if c == 34 else '\\\\' if c == 92 else
                      '\\n' if c == 10 else '\\r' if c == 13 else
                      chr(c) if 32 <= c < 127 else f'\\{c:03o}' for c in chunk)
        f.write(f'    "{esc}"\n')
    f.write(";\n\n#endif\n")
print(f"wrote usb_dac32/roomcorr_web.h: {len(data)} bytes of page")
