#!/usr/bin/env python3
"""Half-band-ish FIR used on-device to take a 96 kHz IR down to 48 kHz."""
import numpy as np, scipy.signal as sig

N = 127                      # odd, so the delay is an exact integer sample
fc = 0.5                     # normalised to the 96 kHz Nyquist -> 24 kHz
h = sig.firwin(N, fc, window=('kaiser', 8.0))
h = h / h.sum()              # unity DC for the signal; the filter gain is fixed by x2

w, H = sig.freqz(h, worN=8192)
f = w / np.pi * 48000        # Hz at the 96 kHz input rate
pb = f <= 20000
sb = f >= 28000
print(f"taps {N}, group delay {(N-1)//2} samples at 96 kHz")
print(f"passband (<=20 kHz) ripple: {20*np.log10(np.abs(H[pb]).max()/np.abs(H[pb]).min()):.3f} dB")
print(f"stopband (>=28 kHz) atten : {-20*np.log10(np.abs(H[sb]).max()):.1f} dB")

with open('usb_dac32/roomcorr_resample.h', 'w') as fo:
    fo.write("/* generated by tools/make_decimator.py - do not edit */\n")
    fo.write("#ifndef _ROOMCORR_RESAMPLE_H_\n#define _ROOMCORR_RESAMPLE_H_\n\n")
    fo.write("#include \"arm_math.h\"\n\n")
    fo.write(f"#define RC_DECIM_TAPS  ({N}U)\n")
    fo.write(f"#define RC_DECIM_DELAY ({(N-1)//2}U)  /* samples at the 96 kHz rate */\n\n")
    fo.write("static const float32_t rc_decim_fir[RC_DECIM_TAPS] = {\n")
    for i in range(0, N, 6):
        fo.write("    " + " ".join(float(v).hex() + "f," for v in h[i:i+6]) + "\n")
    fo.write("};\n\n#endif\n")
print("wrote usb_dac32/roomcorr_resample.h")
