#!/usr/bin/env python3
"""
Turn a room-correction impulse response into a partitioned frequency-domain filter
for the RT1052 convolver.

The IR is resampled to the codec rate (the WM8960 tops out at 48 kHz), split into
P partitions of B taps, and each partition is stored as an N=2B point real FFT in
CMSIS arm_rfft_fast_f32 PACKED layout:

    out[0] = Re(bin 0)      <- DC, real
    out[1] = Re(bin N/2)    <- Nyquist, real
    out[2k], out[2k+1] = Re,Im of bin k,  k = 1 .. N/2-1

Storing it in exactly that layout means the firmware does no conversion at boot.
"""
import argparse, struct, sys
import numpy as np
import scipy.signal as sig
import scipy.io.wavfile as wav

ap = argparse.ArgumentParser()
ap.add_argument('wav', nargs='?', default='Test900.wav')
ap.add_argument('--fs', type=int, default=48000, help='target rate (codec rate)')
ap.add_argument('--block', type=int, default=1024, help='partition size B in frames')
ap.add_argument('--gain-db', type=float, default=0.0, help='extra output gain')
ap.add_argument('--out', default='usb_dac32/roomcorr.bin')
ap.add_argument('--header', default='usb_dac32/roomcorr_params.h')
ap.add_argument('--cdata', default='usb_dac32/roomcorr_data.c')
a = ap.parse_args()

fs_in, x = wav.read(a.wav)
x = x.astype(np.float64)
if x.ndim == 1:
    x = np.column_stack([x, x])
n_in, ch = x.shape
assert ch == 2, f"expected stereo IR, got {ch} channels"

# ---- resample to the codec rate -------------------------------------------------
# Duration is preserved, so 1/duration -- the frequency resolution -- is unchanged.
# Only the 24..48 kHz band is discarded, which the codec cannot reproduce anyway.
g = np.gcd(a.fs, fs_in)
up, dn = a.fs // g, fs_in // g
h = np.stack([sig.resample_poly(x[:, c], up, dn, window=('kaiser', 12.0)) for c in range(2)], axis=1)
# resample_poly preserves SIGNAL amplitude; for a FILTER we want to preserve the
# frequency RESPONSE, so undo the 1/(dn/up) scaling of sum(h) that decimation causes.
h *= dn / up
h *= 10 ** (a.gain_db / 20.0)
n = h.shape[0]
print(f"resampled {fs_in} -> {a.fs} Hz  ({up}/{dn}):  {n_in} -> {n} taps, "
      f"{n_in/fs_in*1000:.1f} ms -> {n/a.fs*1000:.1f} ms")
print(f"frequency resolution: {fs_in/n_in:.3f} Hz -> {a.fs/n:.3f} Hz")

# ---- check the resampling preserved the response --------------------------------
for c in range(2):
    f0 = np.fft.rfftfreq(n_in, 1/fs_in); H0 = np.abs(np.fft.rfft(x[:, c]))
    f1 = np.fft.rfftfreq(n,    1/a.fs);  H1 = np.abs(np.fft.rfft(h[:, c]))
    band = (f1 >= 10) & (f1 <= 20000)
    ref = np.interp(f1[band], f0, H0)
    err = 20*np.log10((H1[band] + 1e-12) / (ref + 1e-12))
    print(f"  ch{c}: 10 Hz-20 kHz magnitude error vs original: "
          f"max {np.abs(err).max():.3f} dB, rms {np.sqrt((err**2).mean()):.4f} dB")

# ---- partition ------------------------------------------------------------------
B = a.block
N = 2 * B
P = int(np.ceil(n / B))
pad = P * B - n
h = np.vstack([h, np.zeros((pad, 2))])
print(f"partitions: P={P} of B={B} (FFT N={N}), zero-padded {pad} taps")

def pack(spec):
    """numpy rfft output (N/2+1 complex) -> CMSIS packed N floats"""
    out = np.empty(N, dtype=np.float32)
    out[0] = spec[0].real
    out[1] = spec[N//2].real
    out[2::2] = spec[1:N//2].real
    out[3::2] = spec[1:N//2].imag
    return out

# filt[ch][p] = packed spectrum of partition p, zero padded to N
filt = np.zeros((2, P, N), dtype=np.float32)
for c in range(2):
    for p in range(P):
        seg = np.zeros(N)
        seg[:B] = h[p*B:(p+1)*B, c]
        filt[c, p] = pack(np.fft.rfft(seg))

# ---- headroom -------------------------------------------------------------------
for c in range(2):
    Hf = np.fft.rfft(h[:, c])
    print(f"  ch{c}: peak |H| = {20*np.log10(np.abs(Hf).max()):+.2f} dB, "
          f"sum|h| = {np.abs(h[:, c]).sum():.3f} "
          f"({20*np.log10(np.abs(h[:, c]).sum()):+.2f} dB worst case)")

# ---- write ----------------------------------------------------------------------
with open(a.out, 'wb') as f:
    f.write(b'RCF1')
    f.write(struct.pack('<IIIII', a.fs, 2, B, P, n))
    f.write(filt.tobytes())          # ch0 partitions then ch1 partitions
sz = 24 + filt.nbytes
print(f"wrote {a.out}: {sz} bytes ({sz/1024:.1f} KiB)")

with open(a.header, 'w') as f:
    f.write("/* generated by tools/make_filter.py - do not edit */\n")
    f.write("#ifndef _ROOMCORR_PARAMS_H_\n#define _ROOMCORR_PARAMS_H_\n\n")
    f.write(f"#define RC_SAMPLE_RATE   ({a.fs}U)\n")
    f.write(f"#define RC_CHANNELS      (2U)\n")
    f.write(f"#define RC_BLOCK         ({B}U)   /* B, frames per partition */\n")
    f.write(f"#define RC_FFT_SIZE      ({N}U)   /* N = 2B */\n")
    f.write(f"#define RC_PARTITIONS    ({P}U)   /* P */\n")
    f.write(f"#define RC_TAPS          ({n}U)\n")
    f.write(f"#define RC_FILTER_BYTES  ({filt.nbytes}U)\n")
    f.write(f"\n#endif\n")
print(f"wrote {a.header}")

# ---- filter as linkable rodata --------------------------------------------------
# Hex-float literals: each value is already exactly representable as float32, so the
# literal round-trips bit-exactly and there is no aliasing games with uint32 arrays.
flat = filt.reshape(-1)
with open(a.cdata, 'w') as f:
    f.write("/* generated by tools/make_filter.py - do not edit */\n")
    f.write('#include "roomcorr.h"\n\n')
    f.write("/* [channel][partition][RC_FFT_SIZE], CMSIS arm_rfft_fast_f32 packed layout */\n")
    f.write("const float32_t rc_filter[RC_CHANNELS * RC_PARTITIONS * RC_FFT_SIZE] = {\n")
    for i in range(0, flat.size, 6):
        f.write("    " + " ".join(float(v).hex() + "f," for v in flat[i:i+6]) + "\n")
    f.write("};\n")
import os
print(f"wrote {a.cdata}: {os.path.getsize(a.cdata)/1024:.0f} KiB of source, "
      f"{flat.size*4/1024:.0f} KiB of rodata")
